### ISSUE TITLE
AttributeError: 'ResNet' object has no attribute 'module'

### ISSUE THREAD

**Issue by luisriera** [yhenon/pytorch-retinanet#126]
Hi,

Could you please help with the following issue?  I am trying to train a CSV dataset using a single GPU with the following packages versions:
* Python = 3.6.0
* Pytorch = 1.2.0

I had some previous error messages that I overcame by passing the environment variable CUDA_VISIBLE_DEVICES=0, I have 2 GPU but aren't the same generation, and comment out the line `retinanet = torch.nn.DataParallel(retinanet).cuda() `.

The error that I am getting now is:
`File "/home/User/miniconda3/envs/pytorch-retinanet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 591, in __getattr__
    type(self).__name__, name))
AttributeError: 'ResNet' object has no attribute 'module'`

**Comment by yhenon** [comment]
Does it work if you keep the line `retinanet = torch.nn.DataParallel(retinanet).cuda()` and pass `CUDA_VISIBLE_DEVICES=0`? It should fall back to the correct behaviour

**Comment by luisriera** [comment]
I get the following:

```
CUDA available: True
No validation annotations provided.
Traceback (most recent call last):
  File "./train.py", line 173, in <module>
    main()
  File "./train.py", line 106, in main
    retinanet.module.freeze_bn()
  File "/home/User/miniconda3/envs/pytorch-retinanet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 591, in __getattr__
    type(self).__name__, name))
AttributeError: 'ResNet' object has no attribute 'module'
```

**Comment by yhenon** [comment]
this is with `retinanet = torch.nn.DataParallel(retinanet).cuda()` ?

**Comment by luisriera** [comment]
After I uncomment the line `retinanet = torch.nn.DataParallel(retinanet).cuda() `

I get the following:

```
CUDA available: True
No validation annotations provided.
Num training images: 84
/home/User/miniconda3/envs/pytorch-retinanet/bin/python: symbol lookup error: /home/User/miniconda3/envs/pytorch-retinanet/lib/python3.6/site-packages/torch/lib/libtorch_python.so: undefined symbol: PySlice_Unpack
/home/User/miniconda3/envs/pytorch-retinanet/bin/python: symbol lookup error: /home/User/miniconda3/envs/pytorch-retinanet/lib/python3.6/site-packages/torch/lib/libtorch_python.so: undefined symbol: PySlice_Unpack
Traceback (most recent call last):
  File "/home/User/miniconda3/envs/pytorch-retinanet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 724, in _try_get_data
    data = self.data_queue.get(timeout=timeout)
  File "/home/User/miniconda3/envs/pytorch-retinanet/lib/python3.6/multiprocessing/queues.py", line 104, in get
    if timeout < 0 or not self._poll(timeout):
  File "/home/User/miniconda3/envs/pytorch-retinanet/lib/python3.6/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/User/miniconda3/envs/pytorch-retinanet/lib/python3.6/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/home/User/miniconda3/envs/pytorch-retinanet/lib/python3.6/multiprocessing/connection.py", line 911, in wait
    ready = selector.select(timeout)
  File "/home/User/miniconda3/envs/pytorch-retinanet/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
  File "/home/User/miniconda3/envs/pytorch-retinanet/lib/python3.6/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 28519) exited unexpectedly with exit code 127. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./train.py", line 173, in <module>
    main()
  File "./train.py", line 117, in main
    for iter_num, data in enumerate(dataloader_train):
  File "/home/User/miniconda3/envs/pytorch-retinanet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 804, in __next__
    idx, data = self._get_data()
  File "/home/User/miniconda3/envs/pytorch-retinanet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 771, in _get_data
    success, data = self._try_get_data()
  File "/home/User/miniconda3/envs/pytorch-retinanet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 737, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 28519) exited unexpectedly

Process finished with exit code 1
```

**Comment by rvandeghen** [comment]
If you don't use `retinanet = torch.nn.DataParallel(retinanet).cuda()` you should write
`retinanet.freeze_bn()` instead of `retinanet.module.freeze_bn()`.
Thus to solve all the issues, make sure that all your call with retinanet don't use `module`.
There is another `.module` that you have to remove in the `csv_eval` file as far as i remember

**Comment by yhenon** [comment]
@luisriera I believe this is fixed by upgrading to python 3.6

@rvandeghen that seems correct, thanks for your input. If you have time to submit a PR to fix this it would be great

**Comment by luisriera** [comment]
Thanks, Guys!
@yhenon I have been using Python 3.6 with Pytorch 1.2 and CUDA 9.1 since I started. I can probably try to update to a newer version and see how it works.

Also, I made the changes as suggested above related to the `.module` but I still get the error.

I track the issue up to the method `def __iter__(self)` at line `yield group` in `class AspectRatioBasedSampler(Sampler)` at the retinanet/dataloader.py module.

**Comment by kruthikakr** [comment]
Any help for this ? facing same issue
